### ISSUE TITLE
More examples and a list of challenges

### ISSUE THREAD

**Issue by hughrawlinson** [gto76/comp-cpp#10]
would be great. I for one don't really know what to expect to be able to do with this. I've written a simple Fibonacci sequence program, and I don't really know where to go next.

**Comment by gto76** [comment]
Yes,
I was just thinking about it today, how cool it would be if it was an actual game with challenges...
With a little story, maybe happening in Britain during WW2, you get hired to work on [Colossus computer](https://en.wikipedia.org/wiki/Colossus_computer)...

**Comment by hughrawlinson** [comment]
That would be great, but it'd also require a _lot_ more work.

**Comment by gto76** [comment]
It's easy to add new instructions (@ketralnis already added two #7), and adding another ram rack wouldn't be too hard either. So it would make sense that you get a new instruction or more ram for every new level (or even better; you would get the instruction that you programmed in last level). You would read input of the challenge from the last address (instead of random value), so that wouldn't require any interface change...

The main chunk of work would be coming up with interesting levels. Also there would have to be a little window for displaying text, save/load mechanism and of course an outro (maybe also some buzzing sounds, a blown vacuum tube here and there... argh feature creep :)

So if anyone has any ideas for the challenges (besides multiplication, division and fibonacci) please post them here!

PS: Of course the ultimate challenge is a [Quine](https://en.wikipedia.org/wiki/Quine_%28computing%29)

**Comment by gto76** [comment]
Enabled noninteractive mode and piped input with this commit: 130d77da2497cf1dcc77cb3c7e4776c6317ab746
For now it's in separate branch, will be merged when finished and documented.

Summary:
Noninteractive mode is started if any input is piped to the
program. In this mode computer prints to 'stdout', there is no
user interface, 'usleep' is not called between cycles, and when
program reads from last address, instead of random value, it
gets one line from stdin (pipe). In this line every '*' is
interpreted as true and all other characters as false. If there
is not enough characters, all missing bits are set to false; and
all characters after the eight one are ignored.

**Comment by gto76** [comment]
I changed my mind, i'm freezing this project and starting a new fork, that will have the non-interactive mode, but also more instructions and separate ram for code and data...

**Comment by hughrawlinson** [comment]
Separate ram would be an awesome feature :smile:

**Comment by gto76** [comment]
I made the "Mark II" version
https://github.com/gto76/comp-m2
