### ISSUE TITLE
Saving and loading executables

### ISSUE THREAD

**Issue by hughrawlinson** [gto76/comp-cpp#11]
Just in ascii form, or in bytes I guess. Tiny files. Wouldn't even need an in-interface load option, just use cli flags :)

**Comment by gto76** [comment]
I can add it, but I think it takes away a bit of authenticity, so I won't document it in readme.

**Comment by hughrawlinson** [comment]
Perfect! :)

**Comment by gto76** [comment]
Done. 5439f865afbf669d6c051d8f224bfcd7b19789ff

Saves ram to file with 's', loads file with first command line argument.

**Comment by gto76** [comment]
Now that save and load are implemented, it would make sense to also make it possible to run in non-interactive mode, so that only output gets printed to stdout. Input to the program could be provided with  arguments following the filename, and it would be red from the last address (instead of a random value). Then multiple machines could be tied together using bash script :)
